import React from 'react';
import { RefreshCw } from 'lucide-react';
import { Button } from '@/components/atoms/button';
import { cn } from '@/utils';

export interface SummaryCardProps {
  className?: string;
  summary: string;
  summaryModel: string | null;
  onRegenerate: () => void;
  isGenerating?: boolean;
}

export function SummaryCard({ className, summary, summaryModel, onRegenerate, isGenerating }: SummaryCardProps) {
  return (
    <div className={cn('space-y-4', className)}>
      <div className="prose prose-sm dark:prose-invert max-w-none">
        {summary.split('\n').map((line, i) => (
          <p key={i} className="text-sm leading-relaxed">
            {line}
          </p>
        ))}
      </div>
      {summaryModel && (
        <p className="text-xs text-muted-foreground">
          Generated by: <span className="font-medium">{summaryModel}</span>
        </p>
      )}
      <Button variant="outline" size="sm" onClick={onRegenerate} disabled={isGenerating} className="gap-2">
        <RefreshCw className={cn('h-4 w-4', isGenerating && 'animate-spin')} />
        Regenerate
      </Button>
    </div>
  );
}
